on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_and_deploy:
    name: Build and deploy to Nuget
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore ./SimpleTextPreprocessor/SimpleTextPreprocessor.csproj

    - name: Build
      run: dotnet restore ./SimpleTextPreprocessor/SimpleTextPreprocessor.csproj --configuration Release --no-restore

    - name: Pack
      run: dotnet pack ./SimpleTextPreprocessor/SimpleTextPreprocessor.csproj --no-restore

    - name: Deploy to Nuget
      run: dotnet nuget push ./SimpleTextPreprocessor/bin/Release/BEHC.SimpleTextPreprocessor.0.1.0.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols
